# Generated by Django 5.0.7 on 2024-07-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invitation',
            name='card_sent',
            field=models.BooleanField(default=False),
        ),
    ]
